insert into authors (author) values ('Drucie Goodbourn');
insert into authors (author) values ('Marcia Aggiss');
insert into authors (author) values ('Giovanni Bigg');
insert into authors (author) values ('Duffie Eynon');
insert into authors (author) values ('Anselma McKennan');
insert into authors (author) values ('Gert Kira');
insert into authors (author) values ('Clerc Djakovic');
insert into authors (author) values ('Stacee Elsy');
insert into authors (author) values ('Dorotea Bonhill');
insert into authors (author) values ('Minni Bunney');
insert into authors (author) values ('Berty Gandley');
insert into authors (author) values ('Raynard Tesdale');
insert into authors (author) values ('Joanna Hutfield');
insert into authors (author) values ('Dannie Glidder');
insert into authors (author) values ('Timmie Adshede');
insert into authors (author) values ('Fernando Neads');
insert into authors (author) values ('Teddy Guilliland');
insert into authors (author) values ('Paloma Grebert');
insert into authors (author) values ('Kristos Usher');
insert into authors (author) values ('Darcey Rohmer');
insert into authors (author) values ('Cristie Isacsson');
insert into authors (author) values ('Lindsay Coutthart');
insert into authors (author) values ('Helyn Schneidar');
insert into authors (author) values ('Bette-ann Askem');
insert into authors (author) values ('Dom Robuchon');


insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Drucie Goodbourn', 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Marcia Aggiss', 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Giovanni Bigg', 'extend strategic e-services', '$272.00', '$151.04');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Duffie Eynon', 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Anselma McKennan', 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Gert Kira', 'architect vertical ROI', '$282.54', '$102.61');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Clerc Djakovic', 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Stacee Elsy', 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Dorotea Bonhill', 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Minni Bunney', 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Berty Gandley', 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Raynard Tesdale', 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Joanna Hutfield', 'scale integrated architectures', '$257.66', '$32.97');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Dannie Glidder', 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Timmie Adshede', 'strategize B2B channels', '$232.27', '$44.83');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Fernando Neads', 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Teddy Guilliland', 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Paloma Grebert', 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Kristos Usher', 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Darcey Rohmer', 'target innovative paradigms', '$298.94', '$130.01');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Cristie Isacsson', 'generate open-source e-business', '$276.57', '$113.25');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Lindsay Coutthart', 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Helyn Schneidar', 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Bette-ann Askem', 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (authorId, title, priceOld, price) values (SELECT id FROM authors WHERE author='Dom Robuchon', 'facilitate efficient eyeballs', '$232.30', '$131.48');
